apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-files-pvc
  labels:
    managed-by: gitops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-db-pvc
  labels:
    managed-by: gitops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path



