# Generated by Django 5.2.1 on 2025-06-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sailors_log", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boat",
            name="type",
        ),
        migrations.AddField(
            model_name="boat",
            name="beam_m",
            field=models.FloatField(blank=True, null=True, verbose_name="Breite (m)"),
        ),
        migrations.AddField(
            model_name="boat",
            name="displacement_kg",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Verdrängung (kg)"
            ),
        ),
        migrations.AddField(
            model_name="boat",
            name="draft_m",
            field=models.FloatField(blank=True, null=True, verbose_name="Tiefgang (m)"),
        ),
        migrations.AddField(
            model_name="boat",
            name="info_url",
            field=models.URLField(blank=True, verbose_name="Weitere Informationen"),
        ),
        migrations.AddField(
            model_name="boat",
            name="length_m",
            field=models.FloatField(blank=True, null=True, verbose_name="Länge (m)"),
        ),
        migrations.AddField(
            model_name="boat",
            name="year_built",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Baujahr"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="distance_nm",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Distanz (Seemeilen)"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="duration",
            field=models.DurationField(blank=True, null=True, verbose_name="Dauer"),
        ),
    ]
