# Generated by Django 5.2.3 on 2025-06-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "info_url",
                    models.URLField(blank=True, verbose_name="Weitere Informationen"),
                ),
                (
                    "year_built",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Baujahr"
                    ),
                ),
                (
                    "length_m",
                    models.FloatField(blank=True, null=True, verbose_name="Länge (m)"),
                ),
                (
                    "beam_m",
                    models.FloatField(blank=True, null=True, verbose_name="Breite (m)"),
                ),
                (
                    "draft_m",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Tiefgang (m)"
                    ),
                ),
                (
                    "displacement_kg",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Verdrängung (kg)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("gpx_file", models.FileField(upload_to="tracks/")),
                ("description", models.TextField(blank=True)),
                (
                    "distance_nm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Distanz (Seemeilen)"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(blank=True, null=True, verbose_name="Dauer"),
                ),
                (
                    "boat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sailors_log_app.boat",
                    ),
                ),
            ],
        ),
    ]
