# Generated by Django 5.2.3 on 2025-06-10 12:26

from django.db import migrations

import sailors_log_app.models


def create_boats(apps, schema_editor):
    Boat = apps.get_model("sailors_log_app", "Boat")

    trigon: sailors_log_app.models.Boat = Boat()
    trigon.name = 'Trigon'
    trigon.info_url = 'https://segelgruppe-kiel.de/trigon/'
    trigon.year_built = 1996
    trigon.length_m = 11.1
    trigon.beam_m = 3.25
    trigon.draft_m = 1.95
    trigon.displacement_kg = 4000
    trigon.save()

    schruvtrekker: sailors_log_app.models.Boat = Boat()
    schruvtrekker.name = 'Schruvtrekker'
    schruvtrekker.info_url = 'https://segelgruppe-kiel.de/schruvtrekker/'
    schruvtrekker.year_built = 1986
    schruvtrekker.length_m = 9.4
    schruvtrekker.beam_m = 3.05
    schruvtrekker.draft_m = 1.5
    schruvtrekker.displacement_kg = 3500
    schruvtrekker.save()

    harald_blauzahn: sailors_log_app.models.Boat = Boat()
    harald_blauzahn.name = 'Harald Blauzahn'
    harald_blauzahn.info_url = 'https://segelgruppe-kiel.de/harald-blauzahn/'
    harald_blauzahn.year_built = 1996
    harald_blauzahn.length_m = 7.64
    harald_blauzahn.beam_m = 2.2
    harald_blauzahn.draft_m = 1.2
    harald_blauzahn.displacement_kg = 2000
    harald_blauzahn.save()

    ingling: sailors_log_app.models.Boat = Boat()
    ingling.name = 'Dipl.Ing.ling'
    ingling.info_url = 'https://segelgruppe-kiel.de/dipl-ing-ling/'
    ingling.length_m = 6.35
    ingling.beam_m = 1.73
    ingling.draft_m = 1.05
    ingling.displacement_kg = 630
    ingling.save()

    filou: sailors_log_app.models.Boat = Boat()
    filou.name = 'Filou'
    filou.info_url = 'https://segelgruppe-kiel.de/filou/'
    filou.length_m = 5.4
    filou.beam_m = 1.8
    filou.draft_m = 1.1
    filou.displacement_kg = 250
    filou.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sailors_log_app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_boats),
    ]
