# Generated by Django 5.2.3 on 2025-06-10 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sailors_log_app", "0002_boats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="WeatherSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("rain", models.FloatField(blank=True, null=True)),
                ("weather_code", models.IntegerField(blank=True, null=True)),
                ("visibility", models.FloatField(blank=True, null=True)),
                ("wind_direction", models.FloatField(blank=True, null=True)),
                ("wind_speed", models.FloatField(blank=True, null=True)),
                ("wind_gusts", models.FloatField(blank=True, null=True)),
                ("cloud_cover", models.FloatField(blank=True, null=True)),
                ("cloud_cover_low", models.FloatField(blank=True, null=True)),
                ("cloud_cover_mid", models.FloatField(blank=True, null=True)),
                ("cloud_cover_high", models.FloatField(blank=True, null=True)),
                ("pressure_msl", models.FloatField(blank=True, null=True)),
                ("surface_pressure", models.FloatField(blank=True, null=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_snapshots",
                        to="sailors_log_app.trip",
                    ),
                ),
            ],
        ),
    ]
